version: '3'

services:
  webapp:
    build: ./
    # image: devoice.azurecr.io/webapp
    command: >
      sh -c "
          python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000"
    volumes:
      - app:/app
      - models:/models
      - cache:/models/cache
    ports:
      - "8000:8000"
    environment:
      - TRANSFORMERS_CACHE=/models/cache
      - TORTOISE_MODELS_DIR=/models
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery

  redis:
    image: "redis:latest"
    ports:
      - "6666:6379"

  celery:
    # image: devoice.azurecr.io/celery
    build: ./
    command: celery -A conf worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - app:/app
    depends_on:
      - redis

volumes:
    app:
    models:
    cache: